### ISSUE TITLE
No compatible con React 18

### ISSUE THREAD

**Issue by jlizanab** [jorgejarai/react-rut-formatter#1]
Al tratar de usarlo con React18 lanza el error "Invalid hook call. Hooks can only be called inside of the body of a function component".

Probando con Reac 18.2.0

**Comment by jorgejarai** [comment]
Hola! Acabo de probar con React 18.2 sobre Vite y no tuve problemas ejecutando los ejemplos de código en el README. Si pudieras darme más información para replicar el error sería fantástico.

**Comment by jorgejarai** [comment]
Cerrando por inactividad. Si tienes algún problema de nuevo, abre otro ticket y lo podemos revisar.
